### PR TITLE
add tel:// links

### PR DESCRIPTION
**Pull request by gomahan**
add tel:// links

### CODE REVIEW

**Review by xyzshantaram — CHANGES_REQUESTED** [review]
First, thanks for your prompt PR. Much appreciated.    
So there's a few things here that stick out to me, that I'd like you to address before I can merge this.

### Major stuff
#### Edge cases
There's practically no error handling here/checking of edge cases. This allows links like
image
And
image
To make it into the DOM.  
At the very least, I'd check for empty strings, slashes and hyphens in strings, and all of that kind of thing before allowing a string to be made into a link. We have to be reasonably sure it's a phone number before rendering it as a card.  
* Side note: It's okay to fall back to rendering it as a plaintext string without the link in case we aren't able to parse it into a phone number. What does not make sense to our code might still make sense to a human.
#### Code repetition
I noticed a lot of repeated code.
```js
    if ("phone" == k) {
        let tempv = v;
        if (tempv.indexOf('/') > 0) {
            let ph = tempv.split("/");
            v = "";
            for (const val of ph) {
                v = v + "  " + getPhoneRow(val.trim());
            }
        } else if (tempv.indexOf(',') > 0) {
            let ph = tempv.split(",");
            v = "";
            for (const val of ph) {
                v = v + "  " + getPhoneRow(val.trim());
            }
        } else {
            v = getPhoneRow(tempv.trim());
        }
    }
```
In this snippet, the following four lines are repeated verbatim:
```js
            let ph = tempv.split("/");
            v = "";
            for (const val of ph) {
                v = v + "  " + getPhoneRow(val.trim());
            }
```  
The only thing that changes is the character in question. This is less than ideal.    
This could be rewritten in the following way (Untested code, for demonstration only):
```js
if (k === "phone") {
    let tempv = v;
    let chars = ["/", ","];
    let ch = '';
    for (const x of chars) {
        if (tempv.includes(x)) {
            ch = x;
        }
    }
    if (ph.length === 1) {
        // none of the characters were found.
        // ideally here you'd make a call as to whether it's really a phone number using
        // a heuristic like length or whether it contains alphabets and then return either
        // a link-ified row or just a plain text row.
        v = getPhoneRow(tempv.trim());
    } else if (Boolean(ch)) { // ch is nonempty
        let ph = tempv.split(ch);
        for (const val of ph) {
            v += `${getPhoneRow(val.trim())} `;
        }
    }
}
```  
### Minor stuff

#### Variable names
Some of your choices for variable names are a little cryptic or redundant.  
For example, `tempv` could just be something like `tmp`.  
`phNo` could be `phoneNo` or similar, and I'm not entirely sure of the purpose of `actPhNo`, which suggests it could do with a little renaming.
Also, `getPhoneRow` is a little weird, since traditionally `getXYZ` is a getter that simply gets + returns a value XYZ from somewhere, but since getPhoneRow is creating a link, I suggest renaming it to createTelLink or similar.

#### Template strings
```js
        return "<a href='tel://" + actPhNo + "'>" + phNo + "</a>"
```
Lines like the above one could be greatly simplified by using template strings.    
For example, the above line would become
```js
        return `<a href="tel://${actPhNo}">${phNo}</a>`
```
#### Whitespace
```js
	if("phone" == k){
		let tempv = v;
		if(tempv.indexOf('/')>0){
			let ph = tempv.split("/");
			v="";
			for (const val of ph) {
				v=v+"  "+getPhoneRow(val.trim());
			}
		}
		else if(tempv.indexOf(',')>0){
			let ph = tempv.split(",");
			v="";
			for (const val of ph) {
				v=v+"  "+getPhoneRow(val.trim());
			}
		}else{
			v= getPhoneRow(tempv.trim());
		}
	}
```
Please try to add proper whitespace to lines like these. It's a lot easier to read that way.    
For example, the above snippet should've been something like:
```js
    if ("phone" == k) {
        let tempv = v;
        if (tempv.indexOf('/') > 0) {
            let ph = tempv.split("/");
            v = "";
            for (const val of ph) {
                v = v + "  " + getPhoneRow(val.trim());
            }
        } else if (tempv.indexOf(',') > 0) {
            let ph = tempv.split(",");
            v = "";
            for (const val of ph) {
                v = v + "  " + getPhoneRow(val.trim());
            }
        } else {
            v = getPhoneRow(tempv.trim());
        }
    }
```
You can see how the spaces make it look that much nicer. You can use an auto-formatter to do this for you. On VSCode I use [HTML-CSS-JS formatter](https://github.com/lonefy/vscode-js-css-html-formatter) by @lonefy.

#### Indentation
Finally, please use 4 spaces instead of tabs in your code. Thank you.

Once again, thanks a lot for your PR, and I'm sure we can get it merged quickly after a little polishing.

**Comment by gomahan** [comment]
Nice comments , I will fix them .  It was quick and I did in the notepad :P I will do a proper one

**Comment by xyzshantaram** [comment]
No problem, thanks.

**Comment by gomahan** [comment]
We are getting error while loading the sheet sometimes. ( Error
Loading data… )Do you know the reason ?

**Comment by gomahan** [comment]
I have tested function individually .  But not tested in the application . Pushed the changes :)

**Comment by gomahan** [comment]
Tested .  Working Fine :)

**Review by xyzshantaram — CHANGES_REQUESTED** [review]
Okay, so, this is a lot better, however, there are still some problems... for example in TN hospitals section,
image
you can see there's a lot of N/As and stuff that make it in.
image
Also these hyphens.
```js
var actualPhNo = phNo.replace(/\D/g, "");
if (!actualPhNo || actualPhNo === '' || actualPhNo.length < 4 || actualPhNo.length > 15)
```

These checks should work to fix it, but they seem to be falling through... Could you investigate?

**Comment by xyzshantaram** [comment]
> We are getting error while loading the sheet sometimes. ( Error
> Loading data… )Do you know the reason ?

Not sure about this. Could you elaborate?

**Comment by gomahan** [comment]
> d work to fix it, but they seem to be falling through... Could you investigate?

But I am not able to understand the issue :(  ..  The above screenshot is showing the fallback condition and showing only the text without link.

**Comment by xyzshantaram** [comment]
Eehhh, you know what, it's probably something with the rest of the row creation logic then. Thanks for your patience!

**Comment by gomahan** [comment]
> > We are getting error while loading the sheet sometimes. ( Error
> > Loading data… )Do you know the reason ?
> 
> Not sure about this. Could you elaborate?
> 
> 



We get error like this in site most of the times

**Comment by xyzshantaram** [comment]
Your guess is as good as mine, it seems to be a Google Sheets bug where the data isn't actually loaded until it's requested and the unfilled sheet is sent back? I don't know ;_;

**Pull request merged**
